image: docker:19.03.1

services:
  - docker:19.03.1-dind

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - build
  - test
  - dockerbuild
  - sonar

cache:
  paths:
    - node_modules/

build:
  stage: build
  image: node:12.14.1-alpine3.11
  script: npm i && npm run build

test:
  stage: test
  image: node:12.14.1-alpine3.11
  script:
    - npm run testgit

dockerbuild:
  stage: dockerbuild
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - /master/

sonar:
  stage: sonar
  image:
    name: sonarsource/sonar-scanner-cli:4.2
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: sonar-scanner
  only:
    - /develop/
    - /master/
