image: docker:19.03.1

services:
  - docker:19.03.1-dind

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"
  KUBE_NAMESPACE: "mspr-ci${CI_BUILD_REF_NAME}"

stages:
  - build
  - test
  - dockerbuild
  - sonardev
  - sonar
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  image: node:12.14.1-alpine3.11
  script: npm i && npm run build

test:
  stage: test
  image: node:12.14.1-alpine3.11
  script:
    - npm run testgit

dockerbuild:
  stage: dockerbuild
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master
    - develop
    - /^release-.*/

sonar-dev:
  stage: sonardev
  image: node:13.8.0-stretch
  script:
    - export SONAR_SCANNER_VERSION=4.0.0.1744
    - export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux
    - rm -rf $SONAR_SCANNER_HOME
    - mkdir -p $SONAR_SCANNER_HOME
    - curl -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
    - unzip $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
    - rm $HOME/.sonar/sonar-scanner.zip
    - export PATH=$SONAR_SCANNER_HOME/bin:$PATH
    - export SONAR_SCANNER_OPTS="-server"
    - sonar-scanner -Dsonar.projectKey=$SONAR_PROJECT -Dsonar.branch.name=dev -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_LOGIN
  only:
    - /develop/

sonar:
  stage: sonar
  image: node:13.8.0-stretch
  script:
    - export SONAR_SCANNER_VERSION=4.0.0.1744
    - export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux
    - rm -rf $SONAR_SCANNER_HOME
    - mkdir -p $SONAR_SCANNER_HOME
    - curl -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
    - unzip $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
    - rm $HOME/.sonar/sonar-scanner.zip
    - export PATH=$SONAR_SCANNER_HOME/bin:$PATH
    - export SONAR_SCANNER_OPTS="-server"
    - sonar-scanner -Dsonar.projectKey=$SONAR_PROJECT -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_LOGIN
  only:
    - /master/

deploy:
  stage: deploy
  image: hublo/kubectl:latest
  script:
    - echo -n $KUBE_CONFIG | base64 -d > ./config
    - kubectl set image deployment/highlanderback $CONTAINER_NAME=$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --kubeconfig ./config --namespace $KUBE_NAMESPACE
  only:
    - develop
    - master
